import "TreeViewNodeViewModel.idl";

namespace MyApp
{
    [default_interface]
    runtimeclass TreeViewHostUserControl : Windows.UI.Xaml.Controls.UserControl
    {
        TreeViewHostUserControl();
		Windows.Foundation.Collections.IObservableVector<TreeViewNodeViewModel> Nodes { get; };
		event Windows.Foundation.EventHandler<TreeViewNodeViewModel> TreeViewNodeSelected;
    }
}
